[package]
name = "cogwarecopilot"
version = "0.0.0"
authors = ["Justin Copenhaver<ninjagecko5000@gmail.com>, Leah Rosenfeld<lynndoxxy@gmail.com>"]
edition = "2021"

[features]
default = ["bsp_rpi3"]
bsp_rpi3 = ["tock-registers"]
bsp_rpi4 = ["tock-registers"]

##--------------------------------------------------------------------------------------------------
## Dependencies
##--------------------------------------------------------------------------------------------------

[dependencies]

# Optional dependencies
tock-registers = { version = "0.8.x", default-features = false, features = ["register_types"], optional = true }
qemu-exit = { version = "3.x.x", optional = true }

# Platform specific dependencies
[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = { version = "9.x.x" }

##--------------------------------------------------------------------------------------------------
## Testing
##--------------------------------------------------------------------------------------------------

[dev-dependencies]

# Unit tests are done in the library part of the kernel.
[lib]
name = "libkernel"
test = false

# Disable unit tests for the kernel binary.
[[bin]]
name = "kernel"
path = "src/main.rs"
test = false

